config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  get 'welcome/about'

  root 'users#show'
  devise_for :users
  resources :users, :only => [:show] do
    resources :items
  end
  get 'users/:id' => 'users#show'

end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :items, dependent: :destroy

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
   devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :email, :password, :password_confirmation, :remember_me) }
   devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:username, :email, :password, :password_confirmation, :remember_me) }
   devise_parameter_sanitizer.for(:account_update) { |u| u.permit( :email, :password, :password_confirmation, :remember_me) }
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def new
    @items = Item.new
  end

  def create
    @user = User.find(params[:user_id])
    @items = @user.items.new(params.require(:item).permit(:name))

    if @items.save
       flash[:notice] = "\"#{@items.name}\" was added to your list."
     else
       flash[:alert] = "There was error saving item."
     end
    redirect_to @user
  end

  def destroy
    @user = User.find(params[:user_id])
    @items = @user.items.find(params[:id])

    if @items.destroy
      flash[:notice] = "\"#{@items.name}\" was deleted successfully."
    else
      flash[:alert] = "There was a error saving post."
    end
      respond_to do |format|
       format.html
       format.js
     end
   end
 end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = params[:id].blank? ? current_user : User.find(params[:id])
    @items = @user.items
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_controller_helper.rb
module ItemsControllerHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/items/_form.html.erb
<%= form_for([@user, @user.items.build]) do |f| %>
  <%= f.text_field :name, placeholder: "New List" %>
  <%= f.submit class: 'btn btn-success' %>
<% end %>

app/views/items/_item.html.erb
<div id="items-<%= item.id %>">
  <p><%= item.name %>
  <%= link_to "delete", user_item_path(item.user, item), method: :delete, class: 'glyphicon glyphicon-ok', remote: true %></p>
  <p><%= distance_of_time_in_words(Time.now, item.created_at + 7.days) + " remaining" %></p>
</div>

app/views/items/destroy.js.erb
<% if @items.destroyed? %>
$('#items-<%= @items.id %>').hide();
$('.notice').html("<div class='alert alert-success'><button type='button' class='close' data-dismiss='alert'>&times;</button><%= flash.now[:notice] %></div>")
<% else %>
 $('.alert').prepend("<div class='alert alert-danger'><button type='button' class='close' data-dismiss='alert'>&times;</button><%= flash.now[:alert] %></div>");
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Todolistapp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% if user_signed_in? %>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
   Signed in as: <strong><%= current_user.username %></strong> |
   <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> -
   <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>

 <% else %>
 <p class="notice"><%= notice %></p>
 <p class="alert"><%= alert %></p>
  <div class="pull-right user-info">
    <%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link'  %> -
    <%= link_to "Sign In", new_user_session_path, :class => 'navbar-link'  %>
  </div>
 <% end %>

<%= yield %>

</body>
</html>

app/views/users/show.html.erb
<h1>Welcome <%= @user.username %></h1>
<h4>Email:<%= @user.email %><h4>
  <div id="items" class='items list-group col-md-8 pull-left'>
    <%= render @items %>
  </div>
  <div class='col-md-6'>
    <%= render partial: 'items/form', locals: {user: @user} %>
  </div>

app/views/welcome/about.html.erb
<h1>Welcome#about</h1>
<p>Find me in app/views/welcome/about.html.erb</p>

app/views/welcome/index.html.erb
<h1>Task Mask</h1>
<p>A application to keep track of weekly tasks.</p>